# Custom Language File for Launcher Customizer

[ejs.app]
title = "Valerium Launcher"

[ejs.landing]

[ejs.settings]
sourceGithubLink = "https://github.com/MidacoYT/ValeriumLauncher"
supportLink = "https://github.com/MidacoYT/ValeriumLauncher/issues"

[ejs.welcome]
welcomeHeader = "VALERIUM"
welcomeDescription = "Bienvenue sur Valerium"
welcomeDescCTA = "Prêt(e) à continuer."
